##
name: 'TYPO3 CI TypoScript Lint'
description: 'GitHub Action that lints your TypoScript code.'
branding:
  icon: check
  color: orange
inputs:
  files:
    description: 'Files you want to lint.'
    required: false
    default: './Configuration/TypoScript'
  config_file:
    description: 'Path to custom configuration'
    required: false
    default: '/Configuration/TsLint.yml'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}
    - ${{ inputs.config_file }}
